/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.user_interface;

import template.date_time;

/**
 *
 * @author user
 */
public class ui_help extends javax.swing.JDialog {

    /**
     * Creates new form ui_help
     */
    
    private final date_time dt;
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ui_help(date_time dt, boolean bl_spp, boolean bl_setoran, boolean bl_tabungan) {
        initComponents();
        setLocationRelativeTo(null);
        this.setModal(true);
        /*BufferedImage cursorImg = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
        Cursor blankCursor = Toolkit.getDefaultToolkit().createCustomCursor(cursorImg, new Point(0, 0), "blank cursor");
        this.getContentPane().setCursor(blankCursor);*/
        check_spp.setSelected(bl_spp);
        check_setoran.setSelected(bl_setoran);
        check_tabungan.setSelected(bl_tabungan);
        this.dt = dt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop1 = new template.desktop();
        check_spp = new javax.swing.JCheckBox();
        check_setoran = new javax.swing.JCheckBox();
        check_tabungan = new javax.swing.JCheckBox();
        open = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        check_spp.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        check_spp.setText("SPP");

        check_setoran.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        check_setoran.setText("Setoran");

        check_tabungan.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        check_tabungan.setText("Tab./T-Angs.");

        open.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Open Key.png"))); // NOI18N
        open.setMnemonic('O');
        open.setText("Open");
        open.setToolTipText("<html><b>[Alt + O]</b> Open</html>");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });

        desktop1.setLayer(check_spp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(check_setoran, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(check_tabungan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(open, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktop1Layout = new javax.swing.GroupLayout(desktop1);
        desktop1.setLayout(desktop1Layout);
        desktop1Layout.setHorizontalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_spp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(open, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(check_setoran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(check_tabungan, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        desktop1Layout.setVerticalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(check_spp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_setoran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_tabungan)
                .addGap(18, 18, 18)
                .addComponent(open)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        dt.repair_button(check_spp.isSelected(), check_setoran.isSelected(), check_tabungan.isSelected());
        this.dispose();
    }//GEN-LAST:event_openActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check_setoran;
    private javax.swing.JCheckBox check_spp;
    private javax.swing.JCheckBox check_tabungan;
    private template.desktop desktop1;
    private javax.swing.JButton open;
    // End of variables declaration//GEN-END:variables
}
