/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.user_interface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ui_pin extends javax.swing.JFrame {

    /**
     * Creates new form ui_pin
     */
    private final ui_server us;
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ui_pin(ui_server us) {
        initComponents();
        setLocationRelativeTo(us);
        frame1.requestFocus();
        this.us = us;
    }

    private String tmp_number = "";
    private final String password = "558801";

    @SuppressWarnings("ResultOfMethodCallIgnored")
    private void set_pin(String number) {
        tmp_number += String.valueOf(number);
        String tmp_format = String.format("%6d", Integer.parseInt(tmp_number));
        for (int i = 0; i < tmp_format.length(); i++) {
            if (tmp_format.charAt(i) != ' ') {
                break;
            } else {
                tmp_format = tmp_format.replace(tmp_format.charAt(i), '_');
            }
        }
        //System.out.println(tmp_number);
        //System.out.println(tmp_format);
        for (int i = 0; i < tmp_format.length(); i++) {
            if (tmp_format.charAt(i) != '_') {
                tmp_format = tmp_format.replace(tmp_format.charAt(i), '*');
            }
        }
        pin.setText(tmp_format);
        if (tmp_number.length() == 6) {
            if (tmp_number.equals(password)) {
                disable_number(false);
                try {
                    Process p = Runtime.getRuntime().exec("shutdown -s -t10 0");
                } catch (IOException ex) {
                    Logger.getLogger(ui_pin.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(us, "<html><b>PIN salah!</b></html>", "Failed", JOptionPane.PLAIN_MESSAGE);
                tmp_number = "";
                pin.setText("______");
            }
        }
        frame1.requestFocus();
    }

    private void disable_number(boolean b) {
        satu.setEnabled(b);
        dua.setEnabled(b);
        tiga.setEnabled(b);
        empat.setEnabled(b);
        lima.setEnabled(b);
        enam.setEnabled(b);
        tujuh.setEnabled(b);
        delapan.setEnabled(b);
        sembilan.setEnabled(b);
        nol.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame1 = new template.frame();
        pin = new javax.swing.JLabel();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        nol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("pinshutdown v.19");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        frame1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                frame1KeyPressed(evt);
            }
        });

        pin.setFont(new java.awt.Font("Cambria Math", 1, 50)); // NOI18N
        pin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pin.setText("______");
        pin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        satu.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });

        dua.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });

        tiga.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });

        empat.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });

        lima.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });

        enam.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });

        tujuh.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });

        delapan.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });

        sembilan.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/return.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        nol.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame1Layout = new javax.swing.GroupLayout(frame1);
        frame1.setLayout(frame1Layout);
        frame1Layout.setHorizontalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame1Layout.createSequentialGroup()
                        .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frame1Layout.createSequentialGroup()
                                .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lima, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enam, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frame1Layout.createSequentialGroup()
                                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tujuh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(frame1Layout.createSequentialGroup()
                                        .addComponent(delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sembilan, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                    .addComponent(nol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(5, 5, 5))
                    .addGroup(frame1Layout.createSequentialGroup()
                        .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frame1Layout.createSequentialGroup()
                                .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))))
        );
        frame1Layout.setVerticalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lima, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enam, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(nol, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({"MalformedFormatString", "ResultOfMethodCallIgnored"})
    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("1");
        }
    }//GEN-LAST:event_satuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("2");
        }
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("3");
        }
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("4");
        }
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("5");
        }
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("6");
        }
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("7");
        }
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("8");
        }
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("9");
        }
    }//GEN-LAST:event_sembilanActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        if (pin.getText().replaceAll("_", "").length() != 6) {
            set_pin("0");
        }
    }//GEN-LAST:event_nolActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        tmp_number = "";
        pin.setText("______");
        disable_number(true);
    }//GEN-LAST:event_refreshActionPerformed

    @SuppressWarnings("static-access")
    private void frame1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frame1KeyPressed
        if (evt.getKeyCode() == evt.VK_1 || evt.getKeyCode() == evt.VK_NUMPAD1) {
            set_pin("1");
        }
        if (evt.getKeyCode() == evt.VK_2 || evt.getKeyCode() == evt.VK_NUMPAD2) {
            set_pin("2");
        }
        if (evt.getKeyCode() == evt.VK_3 || evt.getKeyCode() == evt.VK_NUMPAD3) {
            set_pin("3");
        }
        if (evt.getKeyCode() == evt.VK_4 || evt.getKeyCode() == evt.VK_NUMPAD4) {
            set_pin("4");
        }
        if (evt.getKeyCode() == evt.VK_5 || evt.getKeyCode() == evt.VK_NUMPAD5) {
            set_pin("5");
        }
        if (evt.getKeyCode() == evt.VK_6 || evt.getKeyCode() == evt.VK_NUMPAD6) {
            set_pin("6");
        }
        if (evt.getKeyCode() == evt.VK_7 || evt.getKeyCode() == evt.VK_NUMPAD7) {
            set_pin("7");
        }
        if (evt.getKeyCode() == evt.VK_8 || evt.getKeyCode() == evt.VK_NUMPAD8) {
            set_pin("8");
        }
        if (evt.getKeyCode() == evt.VK_9 || evt.getKeyCode() == evt.VK_NUMPAD9) {
            set_pin("9");
        }
        if (evt.getKeyCode() == evt.VK_0 || evt.getKeyCode() == evt.VK_NUMPAD0) {
            set_pin("0");
        }
        if (evt.getKeyCode() == evt.VK_BACK_SPACE) {
            tmp_number = "";
            pin.setText("______");
            disable_number(true);
        }
    }//GEN-LAST:event_frame1KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private template.frame frame1;
    private javax.swing.JButton lima;
    private javax.swing.JButton nol;
    private javax.swing.JLabel pin;
    private javax.swing.JButton refresh;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
}
