/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.user_interface;

import database.query_control.connection;
import database.query_control.insert.insert_antrian;
import database.query_control.select.select_antrian;
import database.query_control.update.update_antrian;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import server.process_control.create_antrian;
import server.process_control.load_time_service;
import server.process_control.server_registryRMI;
import template.date_time;

/**
 *
 * @author user
 */
public class ui_server extends javax.swing.JFrame {

    /**
     * Creates new form ui_server
     */
    private final date_time dt = new date_time();
    private final connection con = new connection();
    private final load_time_service lts = new load_time_service();
    private final select_antrian sa = new select_antrian();
    private final insert_antrian ia = new insert_antrian();
    private final update_antrian ua = new update_antrian();
    private final create_antrian ca = new create_antrian();
    private final server_registryRMI sr = new server_registryRMI();

    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ui_server() {
        initComponents();
        ImageIcon ico = new ImageIcon((getClass().getResource("/image/IconSBW.png")));
        setIconImage(ico.getImage());
        BufferedImage cursorImg = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
        Cursor blankCursor = Toolkit.getDefaultToolkit().createCustomCursor(cursorImg, new Point(0, 0), "blank cursor");
        this.getContentPane().setCursor(blankCursor);
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        sa.connection(con.connection());
        ia.connection(con.connection());
        ua.connection(con.connection());
        sa.close_admin();
        sa.close_display();
        sa.close_counter();
        sr.registry(sa, ia, ua, ca);
        dt.service_button(spp, setoran, tabungan, help, close);
        dt.repair_button(false, false, false);
        date.setText(dt.date()); // get date
        lts.load();
        dt.run_time(time, lts); // get run_time
        if (spp.isEnabled()) {
            spp.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        desktop1 = new template.desktop();
        panel_a1 = new template.panel_a();
        panel_b1 = new template.panel_b();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_a6 = new template.panel_a();
        spp = new javax.swing.JButton();
        setoran = new javax.swing.JButton();
        tabungan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        help = new javax.swing.JButton();
        close = new javax.swing.JButton();
        panel_a2 = new template.panel_a();
        logo_srv1 = new template.logo_srv();
        panel_a3 = new template.panel_a();
        panel_a4 = new template.panel_a();
        panel_a5 = new template.panel_a();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AntrianSBW v.19");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktop1.setLayout(new java.awt.BorderLayout());

        panel_a1.setPreferredSize(new java.awt.Dimension(715, 391));

        panel_b1.setBackground(new java.awt.Color(255, 255, 102));
        panel_b1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG");

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        panel_a6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        spp.setBackground(new java.awt.Color(153, 255, 255));
        spp.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        spp.setForeground(new java.awt.Color(0, 0, 102));
        spp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/appbar.printer.text.png"))); // NOI18N
        spp.setText("<html>SPP</html>");
        spp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spp.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        spp.setIconTextGap(245);
        spp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sppActionPerformed(evt);
            }
        });

        setoran.setBackground(new java.awt.Color(255, 255, 153));
        setoran.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        setoran.setForeground(new java.awt.Color(0, 0, 102));
        setoran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/appbar.printer.text.png"))); // NOI18N
        setoran.setText("<html>SETORAN</html>");
        setoran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setoran.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        setoran.setIconTextGap(150);
        setoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setoranActionPerformed(evt);
            }
        });

        tabungan.setBackground(new java.awt.Color(153, 255, 153));
        tabungan.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        tabungan.setForeground(new java.awt.Color(0, 0, 102));
        tabungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/appbar.printer.text.png"))); // NOI18N
        tabungan.setText("<html>TAB./TAMBAH ANGSURAN</html>");
        tabungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabungan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        tabungan.setIconTextGap(0);
        tabungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabunganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_a6Layout = new javax.swing.GroupLayout(panel_a6);
        panel_a6.setLayout(panel_a6Layout);
        panel_a6Layout.setHorizontalGroup(
            panel_a6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_a6Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(panel_a6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tabungan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(setoran, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panel_a6Layout.setVerticalGroup(
            panel_a6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_a6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(spp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setoran, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabungan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Hari/Tanggal :");

        date.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(0, 102, 0));
        date.setText("//");

        time.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(0, 102, 0));
        time.setText(":");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Waktu :");

        javax.swing.GroupLayout panel_b1Layout = new javax.swing.GroupLayout(panel_b1);
        panel_b1.setLayout(panel_b1Layout);
        panel_b1Layout.setHorizontalGroup(
            panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(panel_a6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_b1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time)))
                .addContainerGap())
        );
        panel_b1Layout.setVerticalGroup(
            panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(date)
                    .addComponent(time)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_a6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        help.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Help.png"))); // NOI18N
        help.setMnemonic('H');
        help.setText("Help");
        help.setToolTipText("<html><b>Alt + H</b> Help</html>");
        help.setEnabled(false);
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 153, 153));
        close.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        close.setMnemonic('C');
        close.setText("Close");
        close.setToolTipText("<html><b>Alt + C</b> Close</html>");
        close.setEnabled(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_a1Layout = new javax.swing.GroupLayout(panel_a1);
        panel_a1.setLayout(panel_a1Layout);
        panel_a1Layout.setHorizontalGroup(
            panel_a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_a1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(panel_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_a1Layout.setVerticalGroup(
            panel_a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_a1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(help, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        desktop1.add(panel_a1, java.awt.BorderLayout.CENTER);

        panel_a2.setPreferredSize(new java.awt.Dimension(775, 115));
        panel_a2.setLayout(new java.awt.GridBagLayout());

        logo_srv1.setPreferredSize(new java.awt.Dimension(452, 104));

        javax.swing.GroupLayout logo_srv1Layout = new javax.swing.GroupLayout(logo_srv1);
        logo_srv1.setLayout(logo_srv1Layout);
        logo_srv1Layout.setHorizontalGroup(
            logo_srv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        logo_srv1Layout.setVerticalGroup(
            logo_srv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 452;
        gridBagConstraints.ipady = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 165, 6, 158);
        panel_a2.add(logo_srv1, gridBagConstraints);

        desktop1.add(panel_a2, java.awt.BorderLayout.PAGE_START);

        panel_a3.setPreferredSize(new java.awt.Dimension(775, 20));

        javax.swing.GroupLayout panel_a3Layout = new javax.swing.GroupLayout(panel_a3);
        panel_a3.setLayout(panel_a3Layout);
        panel_a3Layout.setHorizontalGroup(
            panel_a3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panel_a3Layout.setVerticalGroup(
            panel_a3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        desktop1.add(panel_a3, java.awt.BorderLayout.PAGE_END);

        panel_a4.setPreferredSize(new java.awt.Dimension(20, 391));

        javax.swing.GroupLayout panel_a4Layout = new javax.swing.GroupLayout(panel_a4);
        panel_a4.setLayout(panel_a4Layout);
        panel_a4Layout.setHorizontalGroup(
            panel_a4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panel_a4Layout.setVerticalGroup(
            panel_a4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        desktop1.add(panel_a4, java.awt.BorderLayout.LINE_END);

        panel_a5.setPreferredSize(new java.awt.Dimension(20, 391));

        javax.swing.GroupLayout panel_a5Layout = new javax.swing.GroupLayout(panel_a5);
        panel_a5.setLayout(panel_a5Layout);
        panel_a5Layout.setHorizontalGroup(
            panel_a5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panel_a5Layout.setVerticalGroup(
            panel_a5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        desktop1.add(panel_a5, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int spp_number = 1000;

    private void sppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sppActionPerformed
        if (spp.isEnabled() != false) {
            load_queue_tiket(spp_number, dt, 1, 1, ia);
        }
    }//GEN-LAST:event_sppActionPerformed

    int setoran_number = 3000;

    private void setoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setoranActionPerformed
        if (setoran.isEnabled() != false) {
            load_queue_tiket(setoran_number, dt, 2, 3, ia);
        }
    }//GEN-LAST:event_setoranActionPerformed

    int tabungan_number = 5000;

    private void tabunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabunganActionPerformed
        if (tabungan.isEnabled() != false) {
            load_queue_tiket(tabungan_number, dt, 3, 5, ia);
        }
    }//GEN-LAST:event_tabunganActionPerformed

    private void load_queue_tiket(int nomor_antrian, date_time dt, int kategori, int kode_nomor, insert_antrian ia) {
        synchronized(this) {
            ca.create(nomor_antrian, sa, dt, kategori, kode_nomor, ia);
            ca.lookup_client_list_normal(sa, ua, 0);
            ca.lookup_display_data(sa, ua);
            ca.lookup_admin_list(sa, ua);
        }
    }
    
    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        if (help.isEnabled() != false) {
            ui_help uh = new ui_help(dt, spp.isEnabled(), setoran.isEnabled(), tabungan.isEnabled());
            //uh.setVisible(true);
            ui_password up = new ui_password(uh);
            up.setVisible(true);
        }
    }//GEN-LAST:event_helpActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sr.close();
    }//GEN-LAST:event_formWindowClosing

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        if (close.isEnabled() != false) {
            ui_pin up = new ui_pin(this);
            up.setVisible(true);
        }
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new ui_server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel date;
    private template.desktop desktop1;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private template.logo_srv logo_srv1;
    private template.panel_a panel_a1;
    private template.panel_a panel_a2;
    private template.panel_a panel_a3;
    private template.panel_a panel_a4;
    private template.panel_a panel_a5;
    private template.panel_a panel_a6;
    private template.panel_b panel_b1;
    private javax.swing.JButton setoran;
    private javax.swing.JButton spp;
    private javax.swing.JButton tabungan;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
