/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.setup_interface;

import admin.process_control.admin_registry;
import database.query_control.connection;
import database.query_control.select.select_attribute;
import database.query_control.update.update_attribute;
import implement.admin.admin;
import java.awt.Component;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 15my15
 */
public class ui_admin extends javax.swing.JFrame {

    /**
     * Creates new form ui_admin
     */
    private final connection con = new connection();
    private final select_attribute sa = new select_attribute();
    private final update_attribute ua = new update_attribute();
    private final admin_registry ar = new admin_registry();
    private InetAddress ip;
    private String admin_kode;

    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ui_admin(String admin_kode, Component com) {
        try {
            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);
            ImageIcon ico = new ImageIcon((getClass().getResource("/image/IconDisplay.png")));
            setIconImage(ico.getImage());
            nomor.requestFocus();
            this.admin_kode = admin_kode;
            sa.connection(con.connection());
            ua.connection(con.connection());
            boolean bl = sa.check_admin_status(Integer.parseInt(admin_kode), com);
            if (bl == false) {
                sa.get_client_list_admin(antrian_biasa);
                sa.get_client_list_cashier(antrian_kasir);
                ip = InetAddress.getLocalHost();
                ua.set_admin(get_data_attribute("Mulai"));
                admin adm = new admin(antrian_biasa, antrian_kasir);
                ar.registry(ip, Integer.parseInt(admin_kode), adm);
            } else {
                System.exit(0);
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(ui_admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ui_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop1 = new template.desktop();
        panel_b1 = new template.panel_b();
        antrian_biasa = new javax.swing.JLabel();
        panel_b2 = new template.panel_b();
        antrian_kasir = new javax.swing.JLabel();
        nomor = new javax.swing.JButton();
        pelayanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AntrianAdmin v.19");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_b1.setBackground(new java.awt.Color(255, 255, 153));
        panel_b1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Antrian_Informasi_PJKartu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Cambria Math", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        antrian_biasa.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        antrian_biasa.setText("<html> <tr style='border-bottom:1pt'> <td>SPP</td> <td>: 0</td> </tr> <tr style='border-bottom:1pt'> <td>Setoran</td> <td>: 0</td> </tr> <tr style='border-bottom:1pt'> <td>Tab./T-Angs.</td> <td>: 0</td> </tr></html>");

        javax.swing.GroupLayout panel_b1Layout = new javax.swing.GroupLayout(panel_b1);
        panel_b1.setLayout(panel_b1Layout);
        panel_b1Layout.setHorizontalGroup(
            panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(antrian_biasa)
                .addGap(3, 3, 3))
        );
        panel_b1Layout.setVerticalGroup(
            panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(antrian_biasa)
                .addGap(3, 3, 3))
        );

        panel_b2.setBackground(new java.awt.Color(255, 255, 153));
        panel_b2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Antrian_Kasir", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Cambria Math", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        antrian_kasir.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        antrian_kasir.setText("<html> <tr style='border-bottom:1pt'> <td>K-SPP</td> <td>: 0</td> </tr> <tr style='border-bottom:1pt'> <td>K-Setoran</td> <td>: 0</td> </tr> <tr style='border-bottom:1pt'> <td>K-Tab./T-Angs.</td> <td>: 0</td></html>");

        javax.swing.GroupLayout panel_b2Layout = new javax.swing.GroupLayout(panel_b2);
        panel_b2.setLayout(panel_b2Layout);
        panel_b2Layout.setHorizontalGroup(
            panel_b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(antrian_kasir)
                .addGap(0, 0, 0))
        );
        panel_b2Layout.setVerticalGroup(
            panel_b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(antrian_kasir, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        nomor.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        nomor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/View File.png"))); // NOI18N
        nomor.setMnemonic('N');
        nomor.setText("Lihat Status Nomor Antrain");
        nomor.setToolTipText("<html><b>[Alt + N]</b> Status Nomor</html>");
        nomor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorActionPerformed(evt);
            }
        });
        nomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomorKeyPressed(evt);
            }
        });

        pelayanan.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        pelayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/View File.png"))); // NOI18N
        pelayanan.setMnemonic('P');
        pelayanan.setText("Lihat Status Pelayanan Meja");
        pelayanan.setToolTipText("<html><b>[Alt + P] Status Pelayanan</b></html>");
        pelayanan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pelayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelayananActionPerformed(evt);
            }
        });
        pelayanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pelayananKeyPressed(evt);
            }
        });

        desktop1.setLayer(panel_b1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(panel_b2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(nomor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(pelayanan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktop1Layout = new javax.swing.GroupLayout(desktop1);
        desktop1.setLayout(desktop1Layout);
        desktop1Layout.setHorizontalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pelayanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        desktop1Layout.setVerticalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panel_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pelayanan)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ua.set_admin(get_data_attribute("Berhenti"));
    }//GEN-LAST:event_formWindowClosing

    private void nomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorActionPerformed
        ui_status_nomor usn = new ui_status_nomor(sa, this);
        usn.setVisible(true);

    }//GEN-LAST:event_nomorActionPerformed

    @SuppressWarnings("static-access")
    private void nomorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomorKeyPressed
        if (evt.getKeyCode() == evt.VK_RIGHT || evt.getKeyCode() == evt.VK_DOWN) {
            nomor.transferFocus();
        }
        if (evt.getKeyCode() == evt.VK_LEFT || evt.getKeyCode() == evt.VK_UP) {
            nomor.transferFocusBackward();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            ui_status_nomor usn = new ui_status_nomor(sa, this);
            usn.setVisible(true);
        }
    }//GEN-LAST:event_nomorKeyPressed

    private void pelayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelayananActionPerformed
        ui_status_meja usm = new ui_status_meja(sa, this);
        usm.setVisible(true);
    }//GEN-LAST:event_pelayananActionPerformed

    @SuppressWarnings("static-access")
    private void pelayananKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pelayananKeyPressed
        if (evt.getKeyCode() == evt.VK_RIGHT || evt.getKeyCode() == evt.VK_DOWN) {
            pelayanan.transferFocus();
        }
        if (evt.getKeyCode() == evt.VK_LEFT || evt.getKeyCode() == evt.VK_UP) {
            pelayanan.transferFocusBackward();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            ui_status_meja usm = new ui_status_meja(sa, this);
            usm.setVisible(true);
        }
    }//GEN-LAST:event_pelayananKeyPressed

    private String[] get_data_attribute(String mulai) {
        String id_admin = admin_kode, hostname = null, status = "0";
        if ("Mulai".equals(mulai)) {
            try {
                ip = InetAddress.getLocalHost();
                hostname = "'" + ip.getHostAddress() + "'";
                status = String.valueOf(1);
            } catch (UnknownHostException ex) {
                Logger.getLogger(ui_admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String data[] = new String[]{id_admin, hostname, status};
        return data;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antrian_biasa;
    private javax.swing.JLabel antrian_kasir;
    private template.desktop desktop1;
    private javax.swing.JButton nomor;
    private template.panel_b panel_b1;
    private template.panel_b panel_b2;
    private javax.swing.JButton pelayanan;
    // End of variables declaration//GEN-END:variables
}
