/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.setup_interface;

import database.query_control.select.select_attribute;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author 15my15
 */
public class ui_status_meja extends javax.swing.JDialog {

    /**
     * Creates new form ui_status_meja
     */
    
    private final select_attribute sa;
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ui_status_meja(select_attribute sa, Component com) {
        initComponents();
        setLocationRelativeTo(com);
        this.setModal(true);
        ImageIcon ico = new ImageIcon((getClass().getResource("/image/IconDisplay.png")));
        setIconImage(ico.getImage());
        ArrayList<String> nomeja_attribute = sa.get_queue_counter();
        for (int i = 0; i < nomeja_attribute.size(); i++) {
            meja.addItem(nomeja_attribute.get(i));
        }
        this.sa = sa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame1 = new template.frame();
        panel_b1 = new template.panel_b();
        jLabel1 = new javax.swing.JLabel();
        meja = new javax.swing.JComboBox<>();
        panel_b2 = new template.panel_b();
        data_meja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MejaAntrianStatus v.19");

        panel_b1.setBackground(new java.awt.Color(255, 255, 153));
        panel_b1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel1.setText("Nomor Meja");

        meja.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        meja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mejaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel_b1Layout = new javax.swing.GroupLayout(panel_b1);
        panel_b1.setLayout(panel_b1Layout);
        panel_b1Layout.setHorizontalGroup(
            panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(meja, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        panel_b1Layout.setVerticalGroup(
            panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(meja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_b2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        data_meja.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        data_meja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        data_meja.setText("<html>\n<tr style='border-bottom:1pt'><td>Nomor Meja</td><td>: -</td></tr>\n<tr style='border-bottom:1pt'><td>Nama Pengguna</td><td>: -</td></tr>\n<tr style='border-bottom:1pt'><td>Kategori</td><td>: -</td></tr>\n<tr style='border-bottom:1pt'><td>Status</td><td>: -</td></tr>\n</html>");
        data_meja.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panel_b2Layout = new javax.swing.GroupLayout(panel_b2);
        panel_b2.setLayout(panel_b2Layout);
        panel_b2Layout.setHorizontalGroup(
            panel_b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(data_meja)
                .addGap(3, 3, 3))
        );
        panel_b2Layout.setVerticalGroup(
            panel_b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_b2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(data_meja, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout frame1Layout = new javax.swing.GroupLayout(frame1);
        frame1.setLayout(frame1Layout);
        frame1Layout.setHorizontalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        frame1Layout.setVerticalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panel_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("static-access")
    private void mejaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mejaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            sa.get_counter_status(data_meja, Integer.parseInt(meja.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_mejaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data_meja;
    private template.frame frame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> meja;
    private template.panel_b panel_b1;
    private template.panel_b panel_b2;
    // End of variables declaration//GEN-END:variables
}
